---

- hosts: test
  become: true
  vars:
    key_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_edition: "ce"
    docker_channel: "edge"
    docker_version: "18.03.0"
    docker_install_docker_compose: True
    docker_compose_version: "1.20.1"
    docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
    docker_apt_cache_time: 86400
    docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

  tasks:
  
  - name: apt-get update
    become: true
    apt:
      update_cache: yes

  - name: remove possible old versions
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-engine
      - docker.io
    become: true

  - name: apt-get update
    become: true
    apt:
      update_cache: yes

  - name: Install Docker and role dependencies
    apt:
      name: "{{ item }}"
      state: "present"
      install_recommends: False
    with_items:
      - "apt-transport-https"
      - "ca-certificates"
      - "software-properties-common"
      - "cron"
      - "curl"

  - name: Get upstream APT GPG key
    apt_key:
      id: "{{ docker_apt_key }}"
      keyserver: "{{ ansible_local.core.keyserver
                     if (ansible_local|d() and ansible_local.core|d() and
                         ansible_local.core.keyserver)
                     else 'hkp://pool.sks-keyservers.net' }}"
      state: "present"

  - name: Configure upstream APT repository
    apt_repository:
      repo: "{{ docker_repository }}"
      state: "present"
      update_cache: True

  - name: Install Docker
    apt:
      name: "docker-{{ docker_edition }}={{ docker_version }}~{{ docker_edition }}-0~{{ ansible_distribution | lower }}"
      state: "present"
      update_cache: True
      install_recommends: False
      cache_valid_time: "{{ docker_apt_cache_time }}"

  - name: Install Docker Compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
      dest: "/usr/local/bin/docker-compose"
      force: True
      owner: "root"
      group: "root"
      mode: "0755"
    when: docker_install_docker_compose

  
  
  - name: Creating Directories
    command: "mkdir -p /auth/ && mkdir -p /var/lib/auth/htpasswd && mkdir -p /docker_registry"
  - name: Copy Password File
    copy: src=/etc/ansible/playbook/files/htpasswd dest=/var/lib/auth/htpasswd mode=0660 backup=no force=yes
  - name: Copy Docker Compose File
    copy: /etc/ansible/playbook/files/docker-compose.yml dest=/docker_registry/docker-compose.yml mode=0444 backup=no force=yes
  - name: Run The Docker Compose File
    command: /usr/local/bin/docker-compose up -d chdir=/docker_registry

  - name: Test Ubuntu Group Present.
    group: 
      name: docker
      state: present

  - name: Add Ubuntu User in Docker Group
    user:
      name: ubuntu
      group: docker

  - name: Restart Docker Service
    command: service docker restart



