registry:
  container_name: registry
  restart: always
  image: registry:2.3.0
  ports:
    - 5000:5000
  environment:
    REGISTRY_AUTH: "htpasswd"
    REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
    REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  volumes:
    - /var/lib/auth:/auth                          
